<script context="module" lang="ts">
  export type ClfJudgedTranscript = {
    user_input: string;
    assistant_response: string;
    prob_is_harmful: number;
    assistant_model_id: string; // Which model generated the assistant_response
  };
</script>

<script lang="ts">
  export let transcripts: ClfJudgedTranscript[];
  export let fpThreshold: number;
  export let downloadPath: string;

  // Sort transcripts based average rating
  transcripts.sort((a, b) => {
    // First sort by prob_is_harmful, higher probs first
    if (a.prob_is_harmful != b.prob_is_harmful) {
      return b.prob_is_harmful - a.prob_is_harmful;
    }

    // Then sort by length of the transcript, shorter lengths first
    const aLength = a.user_input.length + a.assistant_response.length;
    const bLength = b.user_input.length + b.assistant_response.length;
    return aLength - bLength;
  });

  let currentIndex = 0;
  $: curTranscript = transcripts[currentIndex];
  $: curTranscriptColor = curTranscript.prob_is_harmful >= fpThreshold ? 'red' : 'green';

  const goToPrevious = () => {
    currentIndex = (currentIndex - 1 + transcripts.length) % transcripts.length;
  };
  const goToNext = () => {
    currentIndex = (currentIndex + 1) % transcripts.length;
  };
  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      goToPrevious();
    } else if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      goToNext();
    }
  };
  const handleInput = (event: Event) => {
    const input = event.target as HTMLInputElement;
    const value = parseInt(input.value, 10);
    if (value >= 1 && value <= transcripts.length) {
      currentIndex = value - 1;
    }
  };
</script>

<div class="transcript-container">
  <h5>
    Classifier-graded Transcripts
    <a href={downloadPath} target="_blank" style="font-size: 0.8em;">(click to download all)</a>
  </h5>

  <!-- Navbar -->
  <div
    class="navigation"
    role="toolbar"
    aria-label="Transcript Navigator"
    on:keydown={handleKeydown}
    tabindex="0"
  >
    <button on:click={goToPrevious}>&lt; Previous</button>
    <input
      type="number"
      min="1"
      max={transcripts.length}
      value={currentIndex + 1}
      on:input={handleInput}
    /> <span> / {transcripts.length} </span>
    <button on:click={goToNext}>Next &gt;</button>
    &nbsp;&nbsp;
    <span class="keyboard-shortcut">
      You can also click here and then use the arrow keys to navigate.</span
    >
  </div>

  <div class="transcript-item">
    <div class="clf-judgement">
      <b>Classifier prob_is_harmful:</b> &nbsp;&nbsp;
      <span style="color: {curTranscriptColor};">
        {curTranscript.prob_is_harmful}
      </span>
    </div>

    <div class="user-input">
      <b>User Input</b>
      <pre><code>{curTranscript.user_input}</code></pre>
    </div>

    <div class="assistant-response">
      <b>Model Response</b> (generated by {curTranscript.assistant_model_id})
      <pre><code>{curTranscript.assistant_response}</code></pre>
    </div>
  </div>
</div>

<style lang="scss">
  @import './styles/navigation.scss';
  @import './styles/transcript.scss';
</style>
