<script context="module" lang="ts">
  export type Transcript = {
    user_input: string;
    assistant_response: string;
    model_id?: string;
    labels?: Record<string, string>;
  };
</script>

<script lang="ts">
  import { getAvgRating } from '../data-models';

  const capitalizeName = (name: string) => {
    return name.charAt(0).toUpperCase() + name.slice(1);
  };

  export let transcript: Transcript;
</script>

<div class="transcript-container">
  {#if transcript.labels}
    <div class="labels">
      <div>
        <b>Human Labels</b> &nbsp;&nbsp; (avg. rating {getAvgRating(transcript.labels)} / 10)
      </div>
      <ul>
        {#each Object.entries(transcript.labels) as [user, label]}
          <li>{capitalizeName(user)}: &nbsp;&nbsp; {label} / 10</li>
        {/each}
      </ul>
    </div>
  {/if}
  <div class="user-input">
    <b>User Input</b>
    <pre><code>{transcript.user_input}</code></pre>
  </div>
  <div class="assistant-response">
    {#if transcript.model_id}
      <b>Model Response</b> (generated by <b>{transcript.model_id}</b>)
    {:else}
      <b>Model Response</b>
    {/if}
    <pre><code>{transcript.assistant_response}</code></pre>
  </div>
</div>

<style lang="scss">
  @import './styles/transcript.scss';
</style>
